export interface INode {
  avatar_large: string,
  name: string,
  avatar_normal: string,
  title: string,
  url: string,
  topics: number,
  footer: string,
  header: string,
  title_alternative: string,
  avatar_mini: string,
  stars: number,
  root: boolean,
  id: number,
  parent_node_name: string,
}
